spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/t82_user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8000

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  expiration: 1000000

  kafka:
    bootstrap-servers: 34.66.127.160
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#logging:
#  level:
#    org.springframework.security: trace
#  1초 = 1000