spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/t82_user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: 34.66.127.160:9094
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [ 위에서 확인한 클라이언트 ID ]
            client-secret: [ 위에서 확인한 클라이언트 비밀번호 ]
            scope:
              - email
              - profile
server:
  port: 8000

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  expiration: 1000000



#logging:
#  level:
#    org.springframework.security: trace
#  1초 = 1000